version: '3'
services:
  django_db:
    image: postgres:14.2-alpine
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=r00t@R00t
    volumes:
      - postgres-data:/var/lib/postgresql/
volumes:
  postgres-data: